{{- if .Values.k3sToken }}
apiVersion: v1
kind: Secret
metadata:
  name: "vc-token-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.k3sToken | b64enc | quote }}
{{- end }}
